from pydantic_settings import BaseSettings
from functools import lru_cache


class Settings(BaseSettings):
    store_id: str = "STORE_BLR_002"
    api_host: str = "0.0.0.0"
    api_port: int = 8000
    db_path: str = "/data/store_intelligence.db"
    log_level: str = "INFO"
    stale_feed_threshold_minutes: int = 10
    pos_csv_path: str = ""   # empty → skip CSV load (safe default for tests)

    # Seed events generated by the `seed` service (data/mock/generate_sample_events.py).
    # Auto-ingested on startup via the idempotent INSERT-OR-IGNORE path so a fresh
    # `docker compose up` boots with a populated events table, not an empty one.
    seed_events_path: str = "/data/generated/sample_events.jsonl"

    # If pos_csv_path is set but the file is missing on a clean clone (the real
    # organiser CSV under data/resource/ is gitignored), fall back to the mock
    # POS CSV produced by the seed service.
    pos_fallback_csv_path: str = "/data/generated/pos_transactions.csv"

    model_config = {"env_file": ".env", "env_file_encoding": "utf-8"}


@lru_cache
def get_settings() -> Settings:
    return Settings()
